apiVersion : apps/v1
kind: Deployment
metadata:
  name: okrservice 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: okrservice
  template:
    metadata:
      labels:
        app: okrservice 
    spec:
      containers:
        - name: okrservice 
          image: unlockokrregistrydev.azurecr.io/okrservice
          ports:
          - containerPort: 80
          env:
          - name: "ASPNETCORE_ENVIRONMENT"
            value: "Development"
          - name: "ASPNETCORE_FORWARDEDHEADERS_ENABLED"
            value: "true"